<a href="https://colab.research.google.com/github/YOha-Ali/My-Projectsss/blob/main/Tables_by_using_Loop_and_Grade_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 2...😎")
for tables in numbers:
  print ( "2 x ", tables, "=", tables*2 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 3...😎")
for tables in numbers:
  print ( "3 x ", tables, "=", tables*3 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 4...😎")
for tables in numbers:
  print ( "4 x ", tables, "=", tables*4 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 5...😎")
for tables in numbers:
  print ( "5 x ", tables, "=", tables*5 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 6...😎")
for tables in numbers:
  print ( "6 x ", tables, "=", tables*6)

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 7...😎")
for tables in numbers:
  print ( "7 x ", tables, "=", tables*7 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 8...😎")
for tables in numbers:
  print ( "8 x ", tables, "=", tables*8 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 9...😎")
for tables in numbers:
  print ( "9 x ", tables, "=", tables*9 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 12...😎")
for tables in numbers:
  print ( "12 x ", tables, "=", tables*12 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 43...😎")
for tables in numbers:
  print ( "43 x ", tables, "=", tables*43 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 67...😎")
for tables in numbers:
  print ( "67 x ", tables, "=", tables*67 )

numbers : list[int] = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
print("Tables of 82...😎")
for tables in numbers:
  print ( "82 x ", tables, "=", tables*82 )

print("💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖")

Tables of 2...😎
2 x  1 = 2
2 x  2 = 4
2 x  3 = 6
2 x  4 = 8
2 x  5 = 10
2 x  6 = 12
2 x  7 = 14
2 x  8 = 16
2 x  9 = 18
2 x  10 = 20
Tables of 3...😎
3 x  1 = 3
3 x  2 = 6
3 x  3 = 9
3 x  4 = 12
3 x  5 = 15
3 x  6 = 18
3 x  7 = 21
3 x  8 = 24
3 x  9 = 27
3 x  10 = 30
Tables of 4...😎
4 x  1 = 4
4 x  2 = 8
4 x  3 = 12
4 x  4 = 16
4 x  5 = 20
4 x  6 = 24
4 x  7 = 28
4 x  8 = 32
4 x  9 = 36
4 x  10 = 40
Tables of 5...😎
5 x  1 = 5
5 x  2 = 10
5 x  3 = 15
5 x  4 = 20
5 x  5 = 25
5 x  6 = 30
5 x  7 = 35
5 x  8 = 40
5 x  9 = 45
5 x  10 = 50
Tables of 6...😎
6 x  1 = 6
6 x  2 = 12
6 x  3 = 18
6 x  4 = 24
6 x  5 = 30
6 x  6 = 36
6 x  7 = 42
6 x  8 = 48
6 x  9 = 54
6 x  10 = 60
Tables of 7...😎
7 x  1 = 7
7 x  2 = 14
7 x  3 = 21
7 x  4 = 28
7 x  5 = 35
7 x  6 = 42
7 x  7 = 49
7 x  8 = 56
7 x  9 = 63
7 x  10 = 70
Tables of 8...😎
8 x  1 = 8
8 x  2 = 16
8 x  3 = 24
8 x  4 = 32
8 x  5 = 40
8 x  6 = 48
8 x  7 = 56
8 x  8 = 64
8 x  9 = 72
8 x  10 = 80
Tables of 9...😎
9 x  1 = 9
9 x  2 = 18
9 x  3 = 27
9 x  4 = 36
9 x  5 = 45
9 x  6 = 54
9 x  7 = 63
9 x  8 = 72
9 x  9 = 81
9 x  10 = 90
Tables of 12...😎
12 x  1 = 12
12 x  2 = 24
12 x  3 = 36
12 x  4 = 48
12 x  5 = 60
12 x  6 = 72
12 x  7 = 84
12 x  8 = 96
12 x  9 = 108
12 x  10 = 120
Tables of 43...😎
43 x  1 = 43
43 x  2 = 86
43 x  3 = 129
43 x  4 = 172
43 x  5 = 215
43 x  6 = 258
43 x  7 = 301
43 x  8 = 344
43 x  9 = 387
43 x  10 = 430
Tables of 67...😎
67 x  1 = 67
67 x  2 = 134
67 x  3 = 201
67 x  4 = 268
67 x  5 = 335
67 x  6 = 402
67 x  7 = 469
67 x  8 = 536
67 x  9 = 603
67 x  10 = 670
Tables of 82...😎
82 x  1 = 82
82 x  2 = 164
82 x  3 = 246
82 x  4 = 328
82 x  5 = 410
82 x  6 = 492
82 x  7 = 574
82 x  8 = 656
82 x  9 = 738
82 x  10 = 820
💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖💖

In [9]:
percantage = 82

if percantage == 95 :
    print("You got A+ Grade.")
elif percantage <= 95 and percantage > 85:
    print("You got A Grade.")
elif percantage <= 85 and percantage > 75:
    print("You got B+ Grade.")
elif percantage <= 75 and percantage > 65:
    print("You got B Grade.")
elif percantage <= 65 and percantage > 55:
    print("You got C Grade.")
elif percantage <= 55 and percantage > 45:
    print("You got D Grade.")
elif percantage <= 45 and percantage > 35:
    print("You got E Grade.")

else:
    print("You are Fail.")

You got B+ Grade.